apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "secrets-%s" .Release.Name  }}
data:
  SMTP_PASSWORD: {{ .Values.smtp.password | b64enc | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote}}
  FIRST_SUPERUSER_PASSWORD: {{ .Values.superuser.password | b64enc | quote}}
  R5_AUTHORIZATION: {{ .Values.r5.authorisation | b64enc | quote}}
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS.accessKey | b64enc | quote}}
  database-name: {{ .Values.mongodb.auth.database | b64enc | quote}}