apiVersion: v1
kind: Service
metadata:
  name: goat-backend
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app.kubernetes.io/name: goat-backend